### ISSUE TITLE
The total number of tiles should be displayed

### ISSUE THREAD

**Issue by ProGamerGov** [VaKonS/neural-style#4]
In the terminal output near something like: `Processing Image Part #1 `, `Processing Image Part #2 `, etc..., the total number of tiles should be displayed in a form similar to how the current vs total iteration counts are displayed. 

Example: 

`Processing Image Part #1 of 9`

**Comment by VaKonS** [comment]
@ProGamerGov, something like [\[current variant\]](https://github.com/VaKonS/neural-style/tree/2ef9342c369b4a3a7ce985d1ef7c0746d9dbfe5a)?

**Comment by ProGamerGov** [comment]
This issue has been resolved in the latest version.
