### ISSUE TITLE
How does your tiling system avoid lack of memory issues? And possible other applications of your tiling system?

### ISSUE THREAD

**Issue by ProGamerGov** [VaKonS/neural-style#5]
How do you go about dividing the input image into chunks, while not running out of memory? Because there are other areas in which I think that a solution like this might be able help.

Currently, my [neural_style_seg.lua](https://gist.github.com/ProGamerGov/bcbd27a3d2e431adb73ef158d9990d93) script uses more memory for every additional region specified. 

Could your solution be used in a way similar to tiles, only with irregularly shaped regions? And if so, how difficult would it be to apply your tiling solution to neural_style_seg.lua's masked region selection system?

---

In the quest for larger images, I've listed @jcjohnson's suggestions for how we can improve memory efficiency in a way that would allow for larger images: 

> The huge memory spike at the beginning happens when the style image is passed through the network to compute its Gram matrix. In Lua Torch the default behavior when running forwards through a neural network is to store all the intermediate activations for all layers in memory, because you will need them if you want to compute a corresponding backwards pass. This means that when computing the Gram matrix for the style image, neural-style is storing all activations for all layers of the network in memory for the high-resolution style image.
> 
> However in this case there we don't actually need to do a backwards pass; we only need to do a forward pass and store the Gram matrix in memory. Therefore instead of storing the activations from all layers in memory, we only need to store two at a time: we can use layer L to compute layer L+1, then throw away the activations at layer L. With this strategy you'd still see a memory spike when computing the Gram matrix for the style image, but you should be able to use larger style images since you would be bottlenecked by the largest layer, not the sum of all layers.
> 
> Unfortunately this strategy is pretty hairy to implement in Lua Torch, which isn't receiving as many updates these days since the release of PyTorch. I think the best solution might be to rewrite neural-style in PyTorch; this this would make it easy to reduce memory for Gram matrix computation (allowing larger style images), and would also make it much easier to support Tensor cores.

[Source](https://www.reddit.com/r/deepdream/comments/7ptat3/question_regarding_tensor_cores/dskxjxh/)

This also appears to be the same thing: 

> Yes, this is expected. The -style_scale flag sets the size of the style image, and in order to compute the Gram matrix style targets we need to run the (now high-resolution) style image forward through the network.
> 
> This means that (roughly speaking) -style_scale X -image_size Y will require about the same amount of memory as -style_scale 1.0 -image_size X * Y.
> 
> As an interesting side note, computing the Gram style targets only requires a forward pass through the network; in principle this could require very low memory usage if you overwrite the activations of each layer after they are no longer needed. Unfortunately this sort of advanced memory management is not easy to do in Torch; however other frameworks like PyTorch would make this easy.

[Source](https://www.reddit.com/r/deepdream/comments/5tcp7z/has_anyone_else_experienced_high_memory/ddplopz/)

Is this "Layer + 1" computational strategy similar to your tiling method?

**Comment by VaKonS** [comment]
@ProGamerGov, I did not change the processing engine at all.
What this modification does is:
- splits image to tiles;
- processes tiles as usual with 1/3 of total iterations;
- glues processed tiles to full image.

And repeats that 3 times, to make tiles' blended edges stylized and less visible.

So I guess it also uses more memory to process tiles.
At least I did not try to optimize memory usage yet.

**Comment by VaKonS** [comment]
@ProGamerGov, also, if I'm not mistaken, ordinary (not "fast") neural style algorithm does use the backward pass, and therefore the abovementioned "forward pass memory reusing" technic is not applicable here.
Though I didn't dig much into this and could be wrong.

**Comment by ProGamerGov** [comment]
@VaKonS Neural-Style uses the backward pass to add the gradient to the input, I believe. It is theoretically possible to use this memory saving technique in Lua/Torch, but it wouldn't be easy.

I've actually been working on a PyTorch version of Neural-Style (I'm hopefully going to share it as it's own repository soon, if I can get the memory usage to be closer to Neural-Style): https://gist.github.com/ProGamerGov/089a082c2a000d1e1cc034fc75ff5931, but I wouldn't know where to start if I wanted to make a variant of the code which replicates your tiling feature. I also haven't yet figured out how to do what Justin Johnson described in the comments I linked to above.
