### ISSUE TITLE
Error: "inconsistent tensor sizes" with original_colors set to 1

### ISSUE THREAD

**Issue by rahidz** [VaKonS/neural-style#7]
This parameter works:

_th neural_style.lua -style_image paint.jpg -content_image duckpond.JPG -num_iterations 3000 -image_size 500 -output_image pond.png -backend cudnn -cudnn_autotune -style_scale 0.5 -tv_weight 0.000085 -content_weight 5 -style_weight 100 -init image -scale_down -500 -scale_up -4000 -save_iter 1 -overlap_times 2_

This one does not. Setting save_iter to 0 doesn’t work either.

_th neural_style.lua -style_image paint.jpg -content_image duckpond.JPG -num_iterations 3000 -image_size 500 -output_image pond.png -backend cudnn -cudnn_autotune -style_scale 0.5 -tv_weight 0.000085 -content_weight 5 -style_weight 100 -init image -scale_down -500 -scale_up -4000 -save_iter 1 -overlap_times 2 -original_colors 1_

After the first batch of iterations (1000/3000, on size 500 x 375), the following error is displayed:

```
/home/rahid/torch/install/bin/luajit: inconsistent tensor sizes at /home/rahid/torch/pkg/torch/lib/TH/generic/THTensorMath.c:2709
stack traceback:
	[C]: at 0x7f866fc89e40
	[C]: in function 'cat'
	neural_style.lua:688: in function 'original_colors'
	neural_style.lua:249: in function 'maybe_save'
	neural_style.lua:466: in function 'process_img'
	neural_style.lua:546: in function 'main'
	neural_style.lua:844: in main chunk
	[C]: in function 'dofile'
	...ahid/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x56268f8b66f0

```
This is specific to this fork; the original neural-style code works fine with parameters:

_th neural_style.lua -style_image paint.jpg -content_image duckpond.JPG -num_iterations 3000 -image_size 500 -output_image pond.png -backend cudnn -cudnn_autotune -style_scale 0.5 -tv_weight 0.000085 -content_weight 5 -style_weight 100 -init image -original_colors 1_

paint.jpg dimensions are 725 by 500, duckpond.JPG's are 3988 by 2992.

Using Ubuntu 18.04 with a GTX 1060, latest versions of CUDA & cudnn installed.

Thanks for any advice :)

**Comment by VaKonS** [comment]
@rahidz, thanks for finding this out – I forgot to upscale chroma part together with stylized luma.
Please check the recent version, it should work now.

**Comment by rahidz** [comment]
Works perfectly, thank you very much for the fix!
